apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route.yaml

patches:
  - target:
      kind: ClusterRole
      name: rhoai-mcp
    path: clusterrole-patch.yaml
  - target:
      kind: Deployment
      name: rhoai-mcp
    path: deployment-patch.yaml
